name: 'trafiklab_exjobb'
version: '1.0.0'
profile: 'trafiklab_exjobb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  trafiklab_exjobb:
    +schema: analytics
    staging:
      +materialized: view
    marts:
      +materialized: table

