name: 'tafiklab_exjobb'
version: '1.0.0'
config-version: 2
profile: 'stockholm_traffic'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  tafiklab_exjobb:
    +materialized: table  # default for everything unless overridden

    staging:
      +materialized: view
      +schema: analytics_staging   # or just 'staging' if you prefer

    marts:
      +materialized: table
      +schema: analytics_marts     # or just 'marts'

                  # optional
