FROM python:3.11-slim


RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY . .


RUN mkdir -p /app/warehouse
RUN mkdir -p /app/ml_models/saved_models


EXPOSE 8501


HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health || exit 1


CMD ["streamlit", "run", "dashboard/app.py", \
     "--server.port=8501", \
     "--server.address=0.0.0.0", \
     "--server.headless=true", \
     "--browser.gatherUsageStats=false"]